version: '3.1'

networks:
  WirVsVirus:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.10.0/24
       - subnet: 192:168:10::/64

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nah^Rauko1ach2k
    volumes:
      - database
    networks:
      WirVsVirus:
            ipv4_address: 192.168.10.10
            ipv6_address: 192:168:10::10
  dotnet:
    image: eliazdevelops/deinlaufbursche:latest
    restart: always
    environment:
      - ASPNETCORE_URLS=http://192.168.10.20:80/
    networks:
      WirVsVirus:
            ipv4_address: 192.168.10.20
            ipv6_address: 192:168:10::20
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      WirVsVirus:
            ipv4_address: 192.168.10.30
            ipv6_address: 192:168:10::30
            
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  database: